name: calm_circle
description: A guided breathing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/inhale_4seconds.mp3
    - assets/sounds/exhale_4seconds.mp3
    - assets/sounds/exhale_8seconds.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_square.jpg"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icons/app_icon_square.jpg"
